### PR TITLE
Filter condition

### PR DESCRIPTION
**Pull request by pinkie1378**
1. Add a `FILTER` condition for `Elements` and `ElementMap`. There are instances where you only want a subset of elements that match a query string. `FILTER` will only include the elements in a collection that match the specified condition.
2. Decouple `only_if` from `timeout`. Intuitively `only_if` functions as a filter; it should be applicable beyond the scope of defining explicit waits for asynchronous dom changes.

### CODE REVIEW

**Comment by alisaifee** [comment]
Thanks @pinkie1378. While I go through the pull request, would it be possible for you to squash the commits into smaller chunks?

**Comment by pinkie1378** [comment]
You're welcome; I've condensed my changes into 3 commits. Looking forward to your feedback.

**Comment by alisaifee** [comment]
1. Decoupling `only_if` and `timeout` makes sense. :+1: 
2. Coupling the filtering of returned elements based on a specified criteria into the `only_if` argument feels semantically ambiguous to me. One initial thought is to provide the `get_matching` method on all `Condition` subclasses and then add another keyword argument `filter_by` to `Element`/`Elements`/`ElementMap`. For example, if you wanted a list of elements only if some are visible and be able to access only the visible elements you'd write something like `Elements(... only_if = ANY(VISIBLE()), filter_by=VISIBLE())`. An interesting side-effect of this would be if you also wanted to access the invisible elements but only if some are visible you could have another page object property declared as `Elements(...only_if=ANY(VISIBLE()), filter_by=INVISIBLE())`.

**Comment by pinkie1378** [comment]
I've refactored the pull request in response to your comments:

* `only_if` has been restored to its original function of being solely used for explicit waits when coupled with `timeout`.
* The new keyword argument `filter_by` has been added:
    * In `Element`, returns the element if condition is met, else returns `None`.
    * In `Elements` and `ElementMap`, only includes elements that pass the condition in the collection.

**Comment by alisaifee** [comment]
Thanks @pinkie1378, this looks good!

**Comment by pinkie1378** [comment]
You're welcome @alisaifee, glad I was able to contribute.

**Pull request merged**
